export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh-token",
    ME: "/auth/me",
  },
  USERS: {
    LIST: "/users",
    BY_ID: (id: string) => `/users/${id}`,
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
  },
  PRODUCTS: {
    LIST: "/products",
    BY_ID: (id: string) => `/products/${id}`,
    CREATE: "/products",
    UPDATE: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
    SEARCH: "/products/search",
    CATEGORIES: "/products/categories",
  },
  ORDERS: {
    LIST: "/orders",
    BY_ID: (id: string) => `/orders/${id}`,
    CREATE: "/orders",
    CANCEL: (id: string) => `/orders/${id}/cancel`,
  },
  CART: {
    GET: "/cart",
    ADD_ITEM: "/cart/items",
    UPDATE_ITEM: (id: string) => `/cart/items/${id}`,
    REMOVE_ITEM: (id: string) => `/cart/items/${id}`,
    CLEAR: "/cart/clear",
  },
  VERIFICATION: {
    STATUS: "/verification/status",
    IDENTITY: {
      UPLOAD: "/verification/identity/upload",
      STATUS: "/verification/identity/status",
    },
    PHONE: {
      SEND_OTP: "/verification/phone/send-otp",
      VERIFY_OTP: "/verification/phone/verify-otp",
      CHANGE: "/verification/phone/change",
      CHANGE_SEND_OTP: "/verification/phone/change/send-otp",
      CHANGE_VERIFY_OTP: "/verification/phone/change/verify-otp",
    },
    EMAIL: {
      SEND_OTP: "/verification/email/send-otp",
      VERIFY_OTP: "/verification/email/verify-otp",
    },
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    STATS: "/admin/statistics",
    REVENUE_CHART: "/admin/analytics/revenue",
    CATEGORY_CHART: "/admin/analytics/categories",
    USER_ACTIVITY_CHART: "/admin/analytics/user-activity",
    RECENT_USERS: "/admin/recent-users",
    RECENT_PRODUCTS: "/admin/recent-products",
    RECENT_ORDERS: "/admin/recent-orders",
  },
} as const;
