export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    REFRESH: "/auth/refresh-token",
    ME: "/auth/me",
    SEND_VERIFICATION_CODE: "/auth/send-verification-code",
    VERIFICATION: "/auth/send-reset-password-code",
    VERIFY_CODE: "/auth/verify-code",
    RESET_PASSWORD: "/auth/reset-password",
  },
  USERS: {
    LIST: "/users",
    BY_ID: (id: string) => `/users/${id}`,
    UPDATE: (id: string) => `/users/${id}`,
    DELETE: (id: string) => `/users/${id}`,
  },
  PRODUCTS: {
    LIST: "/products",
    BY_ID: (id: string) => `/products/${id}`,
    CREATE: "/products",
    UPDATE: (id: string) => `/products/${id}`,
    DELETE: (id: string) => `/products/${id}`,
    SEARCH: "/products/search",
    CATEGORIES: "/categories",
  },
  LOCATIONS: {
    COUNTRIES: "/countries",
    CITIES_BY_COUNTRY: (countryId: string) => `/countries/${countryId}`,
  },
  ORDERS: {
    LIST: "/orders",
    BY_ID: (id: string) => `/orders/${id}`,
    CREATE: "/orders",
    CANCEL: (id: string) => `/orders/${id}/cancel`,
  },
  CART: {
    GET: "/cart",
    ADD_ITEM: "/cart/items",
    UPDATE_ITEM: (id: string) => `/cart/items/${id}`,
    REMOVE_ITEM: (id: string) => `/cart/items/${id}`,
    CLEAR: "/cart/clear",
  },
  VERIFICATION: {
    STATUS: "/verification/status",
    IDENTITY: {
      UPLOAD: "/verification/identity/upload",
      STATUS: "/verification/identity/status",
    },
    PHONE: {
      SEND_OTP: "/auth/send-verification-code",
      VERIFY_OTP: "/auth/verify-code",
      CHANGE: "/verification/phone/change",
      CHANGE_SEND_OTP: "/verification/phone/change/send-otp",
      CHANGE_VERIFY_OTP: "/verification/phone/change/verify-otp",
    },
    EMAIL: {
      SEND_OTP: "/auth/send-verification-code",
      VERIFY_OTP: "/auth/verify-code",
    },
  },
  PROFILE: {
    CURRENT: "/profile",
  },
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    STATS: "/admin/statistics",
    REVENUE_CHART: "/admin/analytics/revenue",
    CATEGORY_CHART: "/admin/analytics/categories",
    USER_ACTIVITY_CHART: "/admin/analytics/user-activity",
    RECENT_USERS: "/admin/recent-users",
    RECENT_PRODUCTS: "/admin/recent-products",
    RECENT_ORDERS: "/admin/recent-orders",
    LISTINGS: {
      LIST: "/admin/listings",
      BY_ID: (id: string) => `/admin/listings/${id}`,
      APPROVE: (id: string) => `/admin/listings/${id}/approve`,
      REJECT: (id: string) => `/admin/listings/${id}/reject`,
      HIDE: (id: string) => `/admin/listings/${id}/hide`,
      UNHIDE: (id: string) => `/admin/listings/${id}/unhide`,
      BULK_APPROVE: "/admin/listings/bulk/approve",
      BULK_REJECT: "/admin/listings/bulk/reject",
      BULK_DELETE: "/admin/listings/bulk/delete",
    },
    VERIFICATIONS: {
      LIST: "/admin/verifications",
      BY_ID: (id: string) => `/admin/verifications/${id}`,
      APPROVE: (id: string) => `/admin/verifications/${id}/approve`,
      REJECT: (id: string) => `/admin/verifications/${id}/reject`,
    },
    USERS: {
      LIST: "/admin/users",
      BY_ID: (id: string) => `/admin/users/${id}`,
      WARN: (id: string) => `/admin/users/${id}/warn`,
      SUSPEND: (id: string) => `/admin/users/${id}/suspend`,
      BAN: (id: string) => `/admin/users/${id}/ban`,
      UNBAN: (id: string) => `/admin/users/${id}/unban`,
      UPDATE_CHAT_ACCESS: (id: string) => `/admin/users/${id}/chat-access`,
      USER_LISTINGS: (id: string) => `/admin/users/${id}/listings`,
    },
  },
} as const;
